on:
  - push
  - pull_request

name: Go

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: go build ./...
      - run: go test -v ./...
  